/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2+fortran
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/*
 * Formetis project, https://github.com/swig-fortran/formetis
 * Copyright (c) 2021 Oak Ridge National Laboratory, UT-Battelle, LLC.
 * Distributed under an MIT open source license: see LICENSE for details.
 */



#ifndef SWIGFORTRAN
#define SWIGFORTRAN
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};


#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIGVERSION 0x040002 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


extern const char formetis_version[];
extern const int formetis_version_major;
extern const int formetis_version_minor;
extern const int formetis_version_patch;


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


typedef struct {
    void* data;
    size_t size;
} SwigArrayWrapper;


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}


#include <string.h>


#include <stdint.h>


#include <metis.h>


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#define FORMETIS_INT_SIZE 32
#define FORMETIS_REAL_SIZE 32


#if (FORMETIS_INT_SIZE != IDXTYPEWIDTH) \
    || (FORMETIS_REAL_SIZE != REALTYPEWIDTH)
#error "Incompatible Formetis/METIS sizes: you must regenerate this header with SWIG"
#endif

SWIGEXPORT SwigArrayWrapper _wrap_formetis_version_get() {
  SwigArrayWrapper fresult ;
  char *result = 0 ;
  
  result = (char *)(char *)formetis_version;
  fresult.size = strlen((char*)(result));
  fresult.data = (char *)(result);
  return fresult;
}


SWIGEXPORT int _wrap_PartGraphRecursive(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, float *farg9, float *farg10, int32_t *farg11, int32_t *farg12, int32_t *farg13) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  real_t *arg9 = (real_t *) 0 ;
  real_t *arg10 = (real_t *) 0 ;
  idx_t *arg11 = (idx_t *) 0 ;
  idx_t *arg12 = (idx_t *) 0 ;
  idx_t *arg13 = (idx_t *) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (real_t *)(farg9);
  arg10 = (real_t *)(farg10);
  arg11 = (idx_t *)(farg11);
  arg12 = (idx_t *)(farg12);
  arg13 = (idx_t *)(farg13);
  result = (int)METIS_PartGraphRecursive(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_PartGraphKway(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, float *farg9, float *farg10, int32_t *farg11, int32_t *farg12, int32_t *farg13) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  real_t *arg9 = (real_t *) 0 ;
  real_t *arg10 = (real_t *) 0 ;
  idx_t *arg11 = (idx_t *) 0 ;
  idx_t *arg12 = (idx_t *) 0 ;
  idx_t *arg13 = (idx_t *) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (real_t *)(farg9);
  arg10 = (real_t *)(farg10);
  arg11 = (idx_t *)(farg11);
  arg12 = (idx_t *)(farg12);
  arg13 = (idx_t *)(farg13);
  result = (int)METIS_PartGraphKway(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_MeshToDual(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, SwigClassWrapper *farg7, SwigClassWrapper *farg8) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t **arg7 = (idx_t **) 0 ;
  idx_t **arg8 = (idx_t **) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t **)farg7->cptr;
  arg8 = (idx_t **)farg8->cptr;
  result = (int)METIS_MeshToDual(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_MeshToNodal(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, SwigClassWrapper *farg6, SwigClassWrapper *farg7) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t **arg6 = (idx_t **) 0 ;
  idx_t **arg7 = (idx_t **) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t **)farg6->cptr;
  arg7 = (idx_t **)farg7->cptr;
  result = (int)METIS_MeshToNodal(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_PartMeshNodal(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, float *farg8, int32_t *farg9, int32_t *farg10, int32_t *farg11, int32_t *farg12) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  real_t *arg8 = (real_t *) 0 ;
  idx_t *arg9 = (idx_t *) 0 ;
  idx_t *arg10 = (idx_t *) 0 ;
  idx_t *arg11 = (idx_t *) 0 ;
  idx_t *arg12 = (idx_t *) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (real_t *)(farg8);
  arg9 = (idx_t *)(farg9);
  arg10 = (idx_t *)(farg10);
  arg11 = (idx_t *)(farg11);
  arg12 = (idx_t *)(farg12);
  result = (int)METIS_PartMeshNodal(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_PartMeshDual(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, float *farg9, int32_t *farg10, int32_t *farg11, int32_t *farg12, int32_t *farg13) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  real_t *arg9 = (real_t *) 0 ;
  idx_t *arg10 = (idx_t *) 0 ;
  idx_t *arg11 = (idx_t *) 0 ;
  idx_t *arg12 = (idx_t *) 0 ;
  idx_t *arg13 = (idx_t *) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (real_t *)(farg9);
  arg10 = (idx_t *)(farg10);
  arg11 = (idx_t *)(farg11);
  arg12 = (idx_t *)(farg12);
  arg13 = (idx_t *)(farg13);
  result = (int)METIS_PartMeshDual(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_NodeND(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  result = (int)METIS_NodeND(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_Free(void const **farg1) {
  int fresult ;
  void *arg1 = (void *) 0 ;
  int result;
  
  arg1 = (void *)(*farg1);
  result = (int)METIS_Free(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SetDefaultOptions(int32_t *farg1) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  result = (int)METIS_SetDefaultOptions(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_NodeNDP(int32_t const *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t const *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, int32_t *farg9) {
  int fresult ;
  idx_t arg1 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t arg5 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  idx_t *arg9 = (idx_t *) 0 ;
  int result;
  
  arg1 = (idx_t)(*farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t)(*farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (idx_t *)(farg9);
  result = (int)METIS_NodeNDP(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_ComputeVertexSeparator(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  result = (int)METIS_ComputeVertexSeparator(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_NodeRefine(int32_t const *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, float const *farg7) {
  int fresult ;
  idx_t arg1 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  real_t arg7 ;
  int result;
  
  arg1 = (idx_t)(*farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (real_t)(*farg7);
  result = (int)METIS_NodeRefine(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  fresult = (int)(result);
  return fresult;
}



