! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Formetis project, https://github.com/swig-fortran/formetis
! Copyright (c) 2021 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

module forparmetis
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: get_KEEP_BIT
 integer(C_INT), parameter, public :: PARMETIS_MAJOR_VERSION = 4_C_INT
 integer(C_INT), parameter, public :: PARMETIS_MINOR_VERSION = 0_C_INT
 integer(C_INT), parameter, public :: PARMETIS_SUBMINOR_VERSION = 3_C_INT
 public :: PartKway
 public :: PartGeomKway
 public :: PartGeom
 public :: RefineKway
 public :: AdaptiveRepart

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, public :: SWIGTYPE_p_p_int32_t
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: Mesh2Dual
 public :: PartMeshKway
 public :: NodeND
 public :: NodeND2
 public :: SerialNodeND
 ! typedef enum pmoptype_et
 enum, bind(c)
  enumerator :: PARMETIS_OP_KMETIS
  enumerator :: PARMETIS_OP_GKMETIS
  enumerator :: PARMETIS_OP_GMETIS
  enumerator :: PARMETIS_OP_RMETIS
  enumerator :: PARMETIS_OP_AMETIS
  enumerator :: PARMETIS_OP_OMETIS
  enumerator :: PARMETIS_OP_M2DUAL
  enumerator :: PARMETIS_OP_MKMETIS
 end enum
 integer, parameter, public :: pmoptype_et = kind(PARMETIS_OP_KMETIS)
 public :: PARMETIS_OP_KMETIS, PARMETIS_OP_GKMETIS, PARMETIS_OP_GMETIS, PARMETIS_OP_RMETIS, PARMETIS_OP_AMETIS, &
    PARMETIS_OP_OMETIS, PARMETIS_OP_M2DUAL, PARMETIS_OP_MKMETIS
 integer(C_INT), parameter, public :: PARMETIS_MTYPE_LOCAL = 1_C_INT
 integer(C_INT), parameter, public :: PARMETIS_MTYPE_GLOBAL = 2_C_INT
 integer(C_INT), parameter, public :: PARMETIS_SRTYPE_GREEDY = 1_C_INT
 integer(C_INT), parameter, public :: PARMETIS_SRTYPE_2PHASE = 2_C_INT
 integer(C_INT), parameter, public :: PARMETIS_PSR_COUPLED = 1_C_INT
 integer(C_INT), parameter, public :: PARMETIS_PSR_UNCOUPLED = 2_C_INT
 integer(C_INT), parameter, public :: PARMETIS_DBGLVL_TIME = 1_C_INT
 integer(C_INT), parameter, public :: PARMETIS_DBGLVL_INFO = 2_C_INT
 integer(C_INT), parameter, public :: PARMETIS_DBGLVL_PROGRESS = 4_C_INT
 integer(C_INT), parameter, public :: PARMETIS_DBGLVL_REFINEINFO = 8_C_INT
 integer(C_INT), parameter, public :: PARMETIS_DBGLVL_MATCHINFO = 16_C_INT
 integer(C_INT), parameter, public :: PARMETIS_DBGLVL_RMOVEINFO = 32_C_INT
 integer(C_INT), parameter, public :: PARMETIS_DBGLVL_REMAP = 64_C_INT

! WRAPPER DECLARATIONS
interface
function swigc_KEEP_BIT_get() &
bind(C, name="_wrap_KEEP_BIT_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: fresult
end function

function swigc_PartKway(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, farg14, &
  farg15) &
bind(C, name="_wrap_PartKway") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
type(C_PTR), value :: farg8
type(C_PTR), value :: farg9
type(C_PTR), value :: farg10
type(C_PTR), value :: farg11
type(C_PTR), value :: farg12
type(C_PTR), value :: farg13
type(C_PTR), value :: farg14
integer(C_INT), intent(in) :: farg15
integer(C_INT) :: fresult
end function

function swigc_PartGeomKway(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15, farg16, farg17) &
bind(C, name="_wrap_PartGeomKway") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
type(C_PTR), value :: farg8
type(C_PTR), value :: farg9
type(C_PTR), value :: farg10
type(C_PTR), value :: farg11
type(C_PTR), value :: farg12
type(C_PTR), value :: farg13
type(C_PTR), value :: farg14
type(C_PTR), value :: farg15
type(C_PTR), value :: farg16
integer(C_INT), intent(in) :: farg17
integer(C_INT) :: fresult
end function

function swigc_PartGeom(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_PartGeom") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
integer(C_INT), intent(in) :: farg5
integer(C_INT) :: fresult
end function

function swigc_RefineKway(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15) &
bind(C, name="_wrap_RefineKway") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
type(C_PTR), value :: farg8
type(C_PTR), value :: farg9
type(C_PTR), value :: farg10
type(C_PTR), value :: farg11
type(C_PTR), value :: farg12
type(C_PTR), value :: farg13
type(C_PTR), value :: farg14
integer(C_INT), intent(in) :: farg15
integer(C_INT) :: fresult
end function

function swigc_AdaptiveRepart(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15, farg16, farg17) &
bind(C, name="_wrap_AdaptiveRepart") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
type(C_PTR), value :: farg8
type(C_PTR), value :: farg9
type(C_PTR), value :: farg10
type(C_PTR), value :: farg11
type(C_PTR), value :: farg12
type(C_PTR), value :: farg13
type(C_PTR), value :: farg14
type(C_PTR), value :: farg15
type(C_PTR), value :: farg16
integer(C_INT), intent(in) :: farg17
integer(C_INT) :: fresult
end function

function swigc_Mesh2Dual(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8) &
bind(C, name="_wrap_Mesh2Dual") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(SwigClassWrapper), intent(in) :: farg6
type(SwigClassWrapper), intent(in) :: farg7
integer(C_INT), intent(in) :: farg8
integer(C_INT) :: fresult
end function

function swigc_PartMeshKway(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15) &
bind(C, name="_wrap_PartMeshKway") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
type(C_PTR), value :: farg8
type(C_PTR), value :: farg9
type(C_PTR), value :: farg10
type(C_PTR), value :: farg11
type(C_PTR), value :: farg12
type(C_PTR), value :: farg13
type(C_PTR), value :: farg14
integer(C_INT), intent(in) :: farg15
integer(C_INT) :: fresult
end function

function swigc_NodeND(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8) &
bind(C, name="_wrap_NodeND") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
integer(C_INT), intent(in) :: farg8
integer(C_INT) :: fresult
end function

function swigc_NodeND2(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, farg14, &
  farg15) &
bind(C, name="_wrap_NodeND2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
type(C_PTR), value :: farg8
type(C_PTR), value :: farg9
type(C_PTR), value :: farg10
type(C_PTR), value :: farg11
type(C_PTR), value :: farg12
type(C_PTR), value :: farg13
type(C_PTR), value :: farg14
integer(C_INT), intent(in) :: farg15
integer(C_INT) :: fresult
end function

function swigc_SerialNodeND(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8) &
bind(C, name="_wrap_SerialNodeND") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
integer(C_INT), intent(in) :: farg8
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function get_KEEP_BIT() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
integer(C_LONG) :: fresult 

fresult = swigc_KEEP_BIT_get()
swig_result = fresult
end function

function PartKway(vtxdist, xadj, adjncy, vwgt, adjwgt, wgtflag, numflag, ncon, nparts, tpwgts, ubvec, options, edgecut, part, &
  comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: vtxdist
integer(C_INT32_T), dimension(*), target :: xadj
integer(C_INT32_T), dimension(*), target :: adjncy
integer(C_INT32_T), dimension(*), target :: vwgt
integer(C_INT32_T), dimension(*), target :: adjwgt
integer(C_INT32_T), dimension(*), target :: wgtflag
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: ncon
integer(C_INT32_T), dimension(*), target :: nparts
real(C_FLOAT), dimension(*), target :: tpwgts
real(C_FLOAT), dimension(*), target :: ubvec
integer(C_INT32_T), dimension(*), target :: options
integer(C_INT32_T), dimension(*), target :: edgecut
integer(C_INT32_T), dimension(*), target :: part
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 
type(C_PTR) :: farg8 
type(C_PTR) :: farg9 
type(C_PTR) :: farg10 
type(C_PTR) :: farg11 
type(C_PTR) :: farg12 
type(C_PTR) :: farg13 
type(C_PTR) :: farg14 
integer(C_INT) :: farg15 

farg1 = c_loc(vtxdist)
farg2 = c_loc(xadj)
farg3 = c_loc(adjncy)
farg4 = c_loc(vwgt)
farg5 = c_loc(adjwgt)
farg6 = c_loc(wgtflag)
farg7 = c_loc(numflag)
farg8 = c_loc(ncon)
farg9 = c_loc(nparts)
farg10 = c_loc(tpwgts)
farg11 = c_loc(ubvec)
farg12 = c_loc(options)
farg13 = c_loc(edgecut)
farg14 = c_loc(part)
farg15 = comm
fresult = swigc_PartKway(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15)
swig_result = fresult
end function

function PartGeomKway(vtxdist, xadj, adjncy, vwgt, adjwgt, wgtflag, numflag, ndims, xyz, ncon, nparts, tpwgts, ubvec, options, &
  edgecut, part, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: vtxdist
integer(C_INT32_T), dimension(*), target :: xadj
integer(C_INT32_T), dimension(*), target :: adjncy
integer(C_INT32_T), dimension(*), target :: vwgt
integer(C_INT32_T), dimension(*), target :: adjwgt
integer(C_INT32_T), dimension(*), target :: wgtflag
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: ndims
real(C_FLOAT), dimension(*), target :: xyz
integer(C_INT32_T), dimension(*), target :: ncon
integer(C_INT32_T), dimension(*), target :: nparts
real(C_FLOAT), dimension(*), target :: tpwgts
real(C_FLOAT), dimension(*), target :: ubvec
integer(C_INT32_T), dimension(*), target :: options
integer(C_INT32_T), dimension(*), target :: edgecut
integer(C_INT32_T), dimension(*), target :: part
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 
type(C_PTR) :: farg8 
type(C_PTR) :: farg9 
type(C_PTR) :: farg10 
type(C_PTR) :: farg11 
type(C_PTR) :: farg12 
type(C_PTR) :: farg13 
type(C_PTR) :: farg14 
type(C_PTR) :: farg15 
type(C_PTR) :: farg16 
integer(C_INT) :: farg17 

farg1 = c_loc(vtxdist)
farg2 = c_loc(xadj)
farg3 = c_loc(adjncy)
farg4 = c_loc(vwgt)
farg5 = c_loc(adjwgt)
farg6 = c_loc(wgtflag)
farg7 = c_loc(numflag)
farg8 = c_loc(ndims)
farg9 = c_loc(xyz)
farg10 = c_loc(ncon)
farg11 = c_loc(nparts)
farg12 = c_loc(tpwgts)
farg13 = c_loc(ubvec)
farg14 = c_loc(options)
farg15 = c_loc(edgecut)
farg16 = c_loc(part)
farg17 = comm
fresult = swigc_PartGeomKway(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15, farg16, farg17)
swig_result = fresult
end function

function PartGeom(vtxdist, ndims, xyz, part, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: vtxdist
integer(C_INT32_T), dimension(*), target :: ndims
real(C_FLOAT), dimension(*), target :: xyz
integer(C_INT32_T), dimension(*), target :: part
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
integer(C_INT) :: farg5 

farg1 = c_loc(vtxdist)
farg2 = c_loc(ndims)
farg3 = c_loc(xyz)
farg4 = c_loc(part)
farg5 = comm
fresult = swigc_PartGeom(farg1, farg2, farg3, farg4, farg5)
swig_result = fresult
end function

function RefineKway(vtxdist, xadj, adjncy, vwgt, adjwgt, wgtflag, numflag, ncon, nparts, tpwgts, ubvec, options, edgecut, &
  part, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: vtxdist
integer(C_INT32_T), dimension(*), target :: xadj
integer(C_INT32_T), dimension(*), target :: adjncy
integer(C_INT32_T), dimension(*), target :: vwgt
integer(C_INT32_T), dimension(*), target :: adjwgt
integer(C_INT32_T), dimension(*), target :: wgtflag
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: ncon
integer(C_INT32_T), dimension(*), target :: nparts
real(C_FLOAT), dimension(*), target :: tpwgts
real(C_FLOAT), dimension(*), target :: ubvec
integer(C_INT32_T), dimension(*), target :: options
integer(C_INT32_T), dimension(*), target :: edgecut
integer(C_INT32_T), dimension(*), target :: part
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 
type(C_PTR) :: farg8 
type(C_PTR) :: farg9 
type(C_PTR) :: farg10 
type(C_PTR) :: farg11 
type(C_PTR) :: farg12 
type(C_PTR) :: farg13 
type(C_PTR) :: farg14 
integer(C_INT) :: farg15 

farg1 = c_loc(vtxdist)
farg2 = c_loc(xadj)
farg3 = c_loc(adjncy)
farg4 = c_loc(vwgt)
farg5 = c_loc(adjwgt)
farg6 = c_loc(wgtflag)
farg7 = c_loc(numflag)
farg8 = c_loc(ncon)
farg9 = c_loc(nparts)
farg10 = c_loc(tpwgts)
farg11 = c_loc(ubvec)
farg12 = c_loc(options)
farg13 = c_loc(edgecut)
farg14 = c_loc(part)
farg15 = comm
fresult = swigc_RefineKway(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15)
swig_result = fresult
end function

function AdaptiveRepart(vtxdist, xadj, adjncy, vwgt, vsize, adjwgt, wgtflag, numflag, ncon, nparts, tpwgts, ubvec, ipc2redist, &
  options, edgecut, part, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: vtxdist
integer(C_INT32_T), dimension(*), target :: xadj
integer(C_INT32_T), dimension(*), target :: adjncy
integer(C_INT32_T), dimension(*), target :: vwgt
integer(C_INT32_T), dimension(*), target :: vsize
integer(C_INT32_T), dimension(*), target :: adjwgt
integer(C_INT32_T), dimension(*), target :: wgtflag
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: ncon
integer(C_INT32_T), dimension(*), target :: nparts
real(C_FLOAT), dimension(*), target :: tpwgts
real(C_FLOAT), dimension(*), target :: ubvec
real(C_FLOAT), dimension(*), target :: ipc2redist
integer(C_INT32_T), dimension(*), target :: options
integer(C_INT32_T), dimension(*), target :: edgecut
integer(C_INT32_T), dimension(*), target :: part
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 
type(C_PTR) :: farg8 
type(C_PTR) :: farg9 
type(C_PTR) :: farg10 
type(C_PTR) :: farg11 
type(C_PTR) :: farg12 
type(C_PTR) :: farg13 
type(C_PTR) :: farg14 
type(C_PTR) :: farg15 
type(C_PTR) :: farg16 
integer(C_INT) :: farg17 

farg1 = c_loc(vtxdist)
farg2 = c_loc(xadj)
farg3 = c_loc(adjncy)
farg4 = c_loc(vwgt)
farg5 = c_loc(vsize)
farg6 = c_loc(adjwgt)
farg7 = c_loc(wgtflag)
farg8 = c_loc(numflag)
farg9 = c_loc(ncon)
farg10 = c_loc(nparts)
farg11 = c_loc(tpwgts)
farg12 = c_loc(ubvec)
farg13 = c_loc(ipc2redist)
farg14 = c_loc(options)
farg15 = c_loc(edgecut)
farg16 = c_loc(part)
farg17 = comm
fresult = swigc_AdaptiveRepart(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15, farg16, farg17)
swig_result = fresult
end function

function Mesh2Dual(elmdist, eptr, eind, numflag, ncommonnodes, xadj, adjncy, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: elmdist
integer(C_INT32_T), dimension(*), target :: eptr
integer(C_INT32_T), dimension(*), target :: eind
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: ncommonnodes
class(SWIGTYPE_p_p_int32_t), intent(in) :: xadj
class(SWIGTYPE_p_p_int32_t), intent(in) :: adjncy
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(SwigClassWrapper) :: farg6 
type(SwigClassWrapper) :: farg7 
integer(C_INT) :: farg8 

farg1 = c_loc(elmdist)
farg2 = c_loc(eptr)
farg3 = c_loc(eind)
farg4 = c_loc(numflag)
farg5 = c_loc(ncommonnodes)
farg6 = xadj%swigdata
farg7 = adjncy%swigdata
farg8 = comm
fresult = swigc_Mesh2Dual(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8)
swig_result = fresult
end function

function PartMeshKway(elmdist, eptr, eind, elmwgt, wgtflag, numflag, ncon, ncommonnodes, nparts, tpwgts, ubvec, options, &
  edgecut, part, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: elmdist
integer(C_INT32_T), dimension(*), target :: eptr
integer(C_INT32_T), dimension(*), target :: eind
integer(C_INT32_T), dimension(*), target :: elmwgt
integer(C_INT32_T), dimension(*), target :: wgtflag
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: ncon
integer(C_INT32_T), dimension(*), target :: ncommonnodes
integer(C_INT32_T), dimension(*), target :: nparts
real(C_FLOAT), dimension(*), target :: tpwgts
real(C_FLOAT), dimension(*), target :: ubvec
integer(C_INT32_T), dimension(*), target :: options
integer(C_INT32_T), dimension(*), target :: edgecut
integer(C_INT32_T), dimension(*), target :: part
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 
type(C_PTR) :: farg8 
type(C_PTR) :: farg9 
type(C_PTR) :: farg10 
type(C_PTR) :: farg11 
type(C_PTR) :: farg12 
type(C_PTR) :: farg13 
type(C_PTR) :: farg14 
integer(C_INT) :: farg15 

farg1 = c_loc(elmdist)
farg2 = c_loc(eptr)
farg3 = c_loc(eind)
farg4 = c_loc(elmwgt)
farg5 = c_loc(wgtflag)
farg6 = c_loc(numflag)
farg7 = c_loc(ncon)
farg8 = c_loc(ncommonnodes)
farg9 = c_loc(nparts)
farg10 = c_loc(tpwgts)
farg11 = c_loc(ubvec)
farg12 = c_loc(options)
farg13 = c_loc(edgecut)
farg14 = c_loc(part)
farg15 = comm
fresult = swigc_PartMeshKway(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14, farg15)
swig_result = fresult
end function

function NodeND(vtxdist, xadj, adjncy, numflag, options, order, sizes, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: vtxdist
integer(C_INT32_T), dimension(*), target :: xadj
integer(C_INT32_T), dimension(*), target :: adjncy
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: options
integer(C_INT32_T), dimension(*), target :: order
integer(C_INT32_T), dimension(*), target :: sizes
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 
integer(C_INT) :: farg8 

farg1 = c_loc(vtxdist)
farg2 = c_loc(xadj)
farg3 = c_loc(adjncy)
farg4 = c_loc(numflag)
farg5 = c_loc(options)
farg6 = c_loc(order)
farg7 = c_loc(sizes)
farg8 = comm
fresult = swigc_NodeND(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8)
swig_result = fresult
end function

function NodeND2(vtxdist, xadj, adjncy, vwgt, numflag, mtype, rtype, p_nseps, s_nseps, ubfrac, seed, dbglvl, order, sizes, &
  comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: vtxdist
integer(C_INT32_T), dimension(*), target :: xadj
integer(C_INT32_T), dimension(*), target :: adjncy
integer(C_INT32_T), dimension(*), target :: vwgt
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: mtype
integer(C_INT32_T), dimension(*), target :: rtype
integer(C_INT32_T), dimension(*), target :: p_nseps
integer(C_INT32_T), dimension(*), target :: s_nseps
real(C_FLOAT), dimension(*), target :: ubfrac
integer(C_INT32_T), dimension(*), target :: seed
integer(C_INT32_T), dimension(*), target :: dbglvl
integer(C_INT32_T), dimension(*), target :: order
integer(C_INT32_T), dimension(*), target :: sizes
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 
type(C_PTR) :: farg8 
type(C_PTR) :: farg9 
type(C_PTR) :: farg10 
type(C_PTR) :: farg11 
type(C_PTR) :: farg12 
type(C_PTR) :: farg13 
type(C_PTR) :: farg14 
integer(C_INT) :: farg15 

farg1 = c_loc(vtxdist)
farg2 = c_loc(xadj)
farg3 = c_loc(adjncy)
farg4 = c_loc(vwgt)
farg5 = c_loc(numflag)
farg6 = c_loc(mtype)
farg7 = c_loc(rtype)
farg8 = c_loc(p_nseps)
farg9 = c_loc(s_nseps)
farg10 = c_loc(ubfrac)
farg11 = c_loc(seed)
farg12 = c_loc(dbglvl)
farg13 = c_loc(order)
farg14 = c_loc(sizes)
farg15 = comm
fresult = swigc_NodeND2(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, farg14, &
  farg15)
swig_result = fresult
end function

function SerialNodeND(vtxdist, xadj, adjncy, numflag, options, order, sizes, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT32_T), dimension(*), target :: vtxdist
integer(C_INT32_T), dimension(*), target :: xadj
integer(C_INT32_T), dimension(*), target :: adjncy
integer(C_INT32_T), dimension(*), target :: numflag
integer(C_INT32_T), dimension(*), target :: options
integer(C_INT32_T), dimension(*), target :: order
integer(C_INT32_T), dimension(*), target :: sizes
integer(C_INT), intent(in) :: comm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 
integer(C_INT) :: farg8 

farg1 = c_loc(vtxdist)
farg2 = c_loc(xadj)
farg3 = c_loc(adjncy)
farg4 = c_loc(numflag)
farg5 = c_loc(options)
farg6 = c_loc(order)
farg7 = c_loc(sizes)
farg8 = comm
fresult = swigc_SerialNodeND(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8)
swig_result = fresult
end function


end module
