/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2+fortran
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/*
 * Formetis project, https://github.com/swig-fortran/formetis
 * Copyright (c) 2021 Oak Ridge National Laboratory, UT-Battelle, LLC.
 * Distributed under an MIT open source license: see LICENSE for details.
 */



#ifndef SWIGFORTRAN
#define SWIGFORTRAN
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};


#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIGVERSION 0x040002 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


#include <stdint.h>


#include <mpi.h>


#include <parmetis.h>


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}

SWIGEXPORT long _wrap_KEEP_BIT_get() {
  long fresult ;
  long result;
  
  result = (long)(0x40000000L);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT int _wrap_PartKway(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, int32_t *farg9, float *farg10, float *farg11, int32_t *farg12, int32_t *farg13, int32_t *farg14, int const *farg15) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  idx_t *arg9 = (idx_t *) 0 ;
  real_t *arg10 = (real_t *) 0 ;
  real_t *arg11 = (real_t *) 0 ;
  idx_t *arg12 = (idx_t *) 0 ;
  idx_t *arg13 = (idx_t *) 0 ;
  idx_t *arg14 = (idx_t *) 0 ;
  MPI_Comm *arg15 = (MPI_Comm *) 0 ;
  MPI_Comm temp15 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (idx_t *)(farg9);
  arg10 = (real_t *)(farg10);
  arg11 = (real_t *)(farg11);
  arg12 = (idx_t *)(farg12);
  arg13 = (idx_t *)(farg13);
  arg14 = (idx_t *)(farg14);
  temp15 = MPI_Comm_f2c((MPI_Fint)*farg15);
  arg15 = &temp15;
  result = (int)ParMETIS_V3_PartKway(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_PartGeomKway(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, float *farg9, int32_t *farg10, int32_t *farg11, float *farg12, float *farg13, int32_t *farg14, int32_t *farg15, int32_t *farg16, int const *farg17) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  real_t *arg9 = (real_t *) 0 ;
  idx_t *arg10 = (idx_t *) 0 ;
  idx_t *arg11 = (idx_t *) 0 ;
  real_t *arg12 = (real_t *) 0 ;
  real_t *arg13 = (real_t *) 0 ;
  idx_t *arg14 = (idx_t *) 0 ;
  idx_t *arg15 = (idx_t *) 0 ;
  idx_t *arg16 = (idx_t *) 0 ;
  MPI_Comm *arg17 = (MPI_Comm *) 0 ;
  MPI_Comm temp17 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (real_t *)(farg9);
  arg10 = (idx_t *)(farg10);
  arg11 = (idx_t *)(farg11);
  arg12 = (real_t *)(farg12);
  arg13 = (real_t *)(farg13);
  arg14 = (idx_t *)(farg14);
  arg15 = (idx_t *)(farg15);
  arg16 = (idx_t *)(farg16);
  temp17 = MPI_Comm_f2c((MPI_Fint)*farg17);
  arg17 = &temp17;
  result = (int)ParMETIS_V3_PartGeomKway(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_PartGeom(int32_t *farg1, int32_t *farg2, float *farg3, int32_t *farg4, int const *farg5) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  real_t *arg3 = (real_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  MPI_Comm *arg5 = (MPI_Comm *) 0 ;
  MPI_Comm temp5 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (real_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  temp5 = MPI_Comm_f2c((MPI_Fint)*farg5);
  arg5 = &temp5;
  result = (int)ParMETIS_V3_PartGeom(arg1,arg2,arg3,arg4,arg5);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_RefineKway(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, int32_t *farg9, float *farg10, float *farg11, int32_t *farg12, int32_t *farg13, int32_t *farg14, int const *farg15) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  idx_t *arg9 = (idx_t *) 0 ;
  real_t *arg10 = (real_t *) 0 ;
  real_t *arg11 = (real_t *) 0 ;
  idx_t *arg12 = (idx_t *) 0 ;
  idx_t *arg13 = (idx_t *) 0 ;
  idx_t *arg14 = (idx_t *) 0 ;
  MPI_Comm *arg15 = (MPI_Comm *) 0 ;
  MPI_Comm temp15 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (idx_t *)(farg9);
  arg10 = (real_t *)(farg10);
  arg11 = (real_t *)(farg11);
  arg12 = (idx_t *)(farg12);
  arg13 = (idx_t *)(farg13);
  arg14 = (idx_t *)(farg14);
  temp15 = MPI_Comm_f2c((MPI_Fint)*farg15);
  arg15 = &temp15;
  result = (int)ParMETIS_V3_RefineKway(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_AdaptiveRepart(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, int32_t *farg9, int32_t *farg10, float *farg11, float *farg12, float *farg13, int32_t *farg14, int32_t *farg15, int32_t *farg16, int const *farg17) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  idx_t *arg9 = (idx_t *) 0 ;
  idx_t *arg10 = (idx_t *) 0 ;
  real_t *arg11 = (real_t *) 0 ;
  real_t *arg12 = (real_t *) 0 ;
  real_t *arg13 = (real_t *) 0 ;
  idx_t *arg14 = (idx_t *) 0 ;
  idx_t *arg15 = (idx_t *) 0 ;
  idx_t *arg16 = (idx_t *) 0 ;
  MPI_Comm *arg17 = (MPI_Comm *) 0 ;
  MPI_Comm temp17 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (idx_t *)(farg9);
  arg10 = (idx_t *)(farg10);
  arg11 = (real_t *)(farg11);
  arg12 = (real_t *)(farg12);
  arg13 = (real_t *)(farg13);
  arg14 = (idx_t *)(farg14);
  arg15 = (idx_t *)(farg15);
  arg16 = (idx_t *)(farg16);
  temp17 = MPI_Comm_f2c((MPI_Fint)*farg17);
  arg17 = &temp17;
  result = (int)ParMETIS_V3_AdaptiveRepart(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_Mesh2Dual(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, SwigClassWrapper *farg6, SwigClassWrapper *farg7, int const *farg8) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t **arg6 = (idx_t **) 0 ;
  idx_t **arg7 = (idx_t **) 0 ;
  MPI_Comm *arg8 = (MPI_Comm *) 0 ;
  MPI_Comm temp8 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t **)farg6->cptr;
  arg7 = (idx_t **)farg7->cptr;
  temp8 = MPI_Comm_f2c((MPI_Fint)*farg8);
  arg8 = &temp8;
  result = (int)ParMETIS_V3_Mesh2Dual(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_PartMeshKway(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, int32_t *farg9, float *farg10, float *farg11, int32_t *farg12, int32_t *farg13, int32_t *farg14, int const *farg15) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  idx_t *arg9 = (idx_t *) 0 ;
  real_t *arg10 = (real_t *) 0 ;
  real_t *arg11 = (real_t *) 0 ;
  idx_t *arg12 = (idx_t *) 0 ;
  idx_t *arg13 = (idx_t *) 0 ;
  idx_t *arg14 = (idx_t *) 0 ;
  MPI_Comm *arg15 = (MPI_Comm *) 0 ;
  MPI_Comm temp15 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (idx_t *)(farg9);
  arg10 = (real_t *)(farg10);
  arg11 = (real_t *)(farg11);
  arg12 = (idx_t *)(farg12);
  arg13 = (idx_t *)(farg13);
  arg14 = (idx_t *)(farg14);
  temp15 = MPI_Comm_f2c((MPI_Fint)*farg15);
  arg15 = &temp15;
  result = (int)ParMETIS_V3_PartMeshKway(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_NodeND(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int const *farg8) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  MPI_Comm *arg8 = (MPI_Comm *) 0 ;
  MPI_Comm temp8 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  temp8 = MPI_Comm_f2c((MPI_Fint)*farg8);
  arg8 = &temp8;
  result = (int)ParMETIS_V3_NodeND(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_NodeND2(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int32_t *farg8, int32_t *farg9, float *farg10, int32_t *farg11, int32_t *farg12, int32_t *farg13, int32_t *farg14, int const *farg15) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  idx_t *arg8 = (idx_t *) 0 ;
  idx_t *arg9 = (idx_t *) 0 ;
  real_t *arg10 = (real_t *) 0 ;
  idx_t *arg11 = (idx_t *) 0 ;
  idx_t *arg12 = (idx_t *) 0 ;
  idx_t *arg13 = (idx_t *) 0 ;
  idx_t *arg14 = (idx_t *) 0 ;
  MPI_Comm *arg15 = (MPI_Comm *) 0 ;
  MPI_Comm temp15 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  arg8 = (idx_t *)(farg8);
  arg9 = (idx_t *)(farg9);
  arg10 = (real_t *)(farg10);
  arg11 = (idx_t *)(farg11);
  arg12 = (idx_t *)(farg12);
  arg13 = (idx_t *)(farg13);
  arg14 = (idx_t *)(farg14);
  temp15 = MPI_Comm_f2c((MPI_Fint)*farg15);
  arg15 = &temp15;
  result = (int)ParMETIS_V32_NodeND(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_SerialNodeND(int32_t *farg1, int32_t *farg2, int32_t *farg3, int32_t *farg4, int32_t *farg5, int32_t *farg6, int32_t *farg7, int const *farg8) {
  int fresult ;
  idx_t *arg1 = (idx_t *) 0 ;
  idx_t *arg2 = (idx_t *) 0 ;
  idx_t *arg3 = (idx_t *) 0 ;
  idx_t *arg4 = (idx_t *) 0 ;
  idx_t *arg5 = (idx_t *) 0 ;
  idx_t *arg6 = (idx_t *) 0 ;
  idx_t *arg7 = (idx_t *) 0 ;
  MPI_Comm *arg8 = (MPI_Comm *) 0 ;
  MPI_Comm temp8 ;
  int result;
  
  arg1 = (idx_t *)(farg1);
  arg2 = (idx_t *)(farg2);
  arg3 = (idx_t *)(farg3);
  arg4 = (idx_t *)(farg4);
  arg5 = (idx_t *)(farg5);
  arg6 = (idx_t *)(farg6);
  arg7 = (idx_t *)(farg7);
  temp8 = MPI_Comm_f2c((MPI_Fint)*farg8);
  arg8 = &temp8;
  result = (int)ParMETIS_SerialNodeND(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  fresult = (int)(result);
  return fresult;
}



